# Generated by Django 2.0.5 on 2018-05-27 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cover_capitulo', models.ImageField(upload_to='static')),
                ('sinopsis', models.CharField(max_length=305)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen')], default='ACC', max_length=20)),
                ('sinopsis', models.TextField()),
                ('fecha_de_lanzamiento', models.DateField()),
                ('fecha_de_publicacion', models.DateField(default=django.utils.timezone.now)),
                ('cast', models.CharField(max_length=200)),
                ('trailer_link', models.TextField()),
                ('serie_cover', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada_name', models.CharField(max_length=11)),
                ('Serie', models.ManyToManyField(to='series.Series')),
                ('capitulos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.Capitulos')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='tem',
            field=models.ManyToManyField(to='series.Temporada'),
        ),
    ]
