# Generated by Django 2.0.5 on 2018-05-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20180526_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='Serie',
        ),
    ]
