# Generated by Django 2.0.5 on 2018-05-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_remove_temporada_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='capitulos',
        ),
        migrations.AddField(
            model_name='temporada',
            name='capitulos',
            field=models.ManyToManyField(blank=True, null=True, to='series.Capitulos'),
        ),
    ]
