# Generated by Django 2.0.5 on 2018-05-27 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20180526_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='capitulos',
            field=models.ManyToManyField(blank=True, to='series.Capitulos'),
        ),
    ]
