# Generated by Django 2.0.5 on 2018-05-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_auto_20180526_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
    ]
