# Generated by Django 2.0.5 on 2018-05-27 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_temporada_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='serie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='tem',
            field=models.ManyToManyField(blank=True, to='series.Temporada'),
        ),
    ]
