# Generated by Django 2.0.5 on 2018-05-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_auto_20180527_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='serie',
        ),
        migrations.AddField(
            model_name='temporada',
            name='nombre_serie',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='temporada_name',
            field=models.CharField(max_length=14),
        ),
    ]
