# Generated by Django 2.0.5 on 2018-06-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_auto_20180612_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
