# Generated by Django 2.0.5 on 2018-06-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0012_series_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
