# Generated by Django 2.0.5 on 2018-06-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0013_series_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='emision',
            field=models.BooleanField(default=False),
        ),
    ]
