# Generated by Django 2.0.5 on 2018-06-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0014_series_emision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votacion',
            old_name='pelicula',
            new_name='series',
        ),
    ]
