# Generated by Django 2.0.5 on 2018-06-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0015_auto_20180613_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='series.Series'),
        ),
    ]
