# Generated by Django 2.0.5 on 2018-06-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0017_auto_20180613_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='ver_mas_tarde',
            field=models.ManyToManyField(blank=True, related_name='ver_mas_tarde_series', to='series.Vermastarde'),
        ),
    ]
