# Generated by Django 2.0.5 on 2018-06-14 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0018_auto_20180613_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vermastarde',
            name='favoritos',
        ),
        migrations.RemoveField(
            model_name='vermastarde',
            name='serie',
        ),
        migrations.AlterField(
            model_name='series',
            name='ver_mas_tarde',
            field=models.ManyToManyField(blank=True, related_name='ver_mas_tarde_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vermastarde',
        ),
    ]
