# Generated by Django 2.0.5 on 2018-06-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0019_auto_20180614_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vermastarde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='votacion',
            name='fecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Vermastarde'),
        ),
    ]
