# Generated by Django 2.0.5 on 2018-06-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0020_auto_20180614_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
