# Generated by Django 2.0.5 on 2018-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0021_auto_20180614_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
