# Generated by Django 2.0.5 on 2018-06-14 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0022_auto_20180614_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 13, 32, 27, 203645)),
        ),
    ]
