# Generated by Django 2.0.5 on 2018-06-14 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0023_auto_20180614_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 14, 0, 38, 299338)),
        ),
        migrations.RemoveField(
            model_name='votacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='votacion',
            name='fecha',
            field=models.ManyToManyField(blank=True, null=True, to='series.Vermastarde'),
        ),
    ]
