# Generated by Django 2.0.5 on 2018-06-14 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0024_auto_20180614_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 14, 1, 9, 848353)),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='fecha',
            field=models.ManyToManyField(blank=True, to='series.Vermastarde'),
        ),
    ]
