# Generated by Django 2.0.5 on 2018-06-14 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0025_auto_20180614_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 18, 2, 51, 213995, tzinfo=utc)),
        ),
    ]
