# Generated by Django 2.0.5 on 2018-06-14 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0026_auto_20180614_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
