# Generated by Django 2.0.5 on 2018-06-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0040_auto_20180614_1739'),
        ('series', '0028_auto_20180614_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='series',
            name='ver_mas_tarde',
        ),
        migrations.DeleteModel(
            name='Vermastarde',
        ),
    ]
