# Generated by Django 2.0.5 on 2018-06-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0029_auto_20180614_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='num_episodio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='temporadaa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporada_del_capitulo', to='series.Temporada'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='num_temporada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
