# Generated by Django 2.0.5 on 2018-06-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0030_auto_20180615_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
