# Generated by Django 2.0.5 on 2018-06-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0032_auto_20180615_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True),
        ),
    ]
