# Generated by Django 2.0.5 on 2018-06-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0033_auto_20180615_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='capitulos',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
