# Generated by Django 2.0.5 on 2018-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0034_auto_20180615_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='openload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='rapidvideo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='streamago',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='tag1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='tag2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='tag3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='vidoza',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='webtorrent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
