# Generated by Django 2.0.5 on 2018-06-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0035_auto_20180617_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
