# Generated by Django 2.0.5 on 2018-06-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0036_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='pais',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
