# Generated by Django 2.0.5 on 2018-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0039_series_reparto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='cast',
        ),
        migrations.AlterField(
            model_name='series',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='series',
            name='trailer_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
