# Generated by Django 2.0.5 on 2018-07-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0040_auto_20180701_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitcount_Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitcount', models.IntegerField(default=0)),
                ('publish', models.DateField(auto_now_add=True)),
                ('expired', models.DateTimeField(auto_now=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series')),
            ],
        ),
    ]
