# Generated by Django 2.0.5 on 2018-07-03 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0043_temporada_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='on',
        ),
        migrations.AddField(
            model_name='temporada',
            name='on',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
