# Generated by Django 2.0.5 on 2018-07-03 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0044_auto_20180703_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='on',
            field=models.ManyToManyField(related_name='on', to=settings.AUTH_USER_MODEL),
        ),
    ]
