# Generated by Django 2.0.5 on 2018-07-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0045_auto_20180703_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='capitulos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Capitulos'),
        ),
        migrations.AlterField(
            model_name='series',
            name='genero',
            field=models.CharField(choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('DOCU', 'Documental'), ('ROM', 'Romance'), ('FANT', 'Fantasia')], default='ACC', max_length=20),
        ),
        migrations.AlterField(
            model_name='series',
            name='genero2',
            field=models.CharField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('DOCU', 'Documental'), ('ROM', 'Romance'), ('FANT', 'Fantasia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_id', to='series.Series'),
        ),
    ]
