# Generated by Django 2.0.5 on 2018-07-05 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0046_auto_20180704_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='unvote_capitulo',
            field=models.ManyToManyField(related_name='unvote_capitulo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='vote_capitulo',
            field=models.ManyToManyField(related_name='vote_capitulo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hitcount_series',
            name='capitulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Capitulos'),
        ),
        migrations.AlterField(
            model_name='hitcount_series',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
    ]
