# Generated by Django 2.0.5 on 2018-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0049_auto_20180705_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='reportes',
            field=models.IntegerField(default=0),
        ),
    ]
