# Generated by Django 2.0.5 on 2018-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0050_capitulos_reportes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='reportes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
