# Generated by Django 2.0.5 on 2018-12-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0052_auto_20181208_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitcount_series',
            name='hitcount_ever',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hitcount_series',
            name='expired',
            field=models.DateTimeField(),
        ),
    ]
