# Generated by Django 2.0.5 on 2019-01-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0053_auto_20181210_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='nombre_original',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='genero3',
            field=models.CharField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('DOCU', 'Documental'), ('ROM', 'Romance'), ('FANT', 'Fantasia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='titulo_original',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capitulos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
