# Generated by Django 2.0.5 on 2019-01-28 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0056_auto_20190127_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='on',
            field=models.ManyToManyField(null=True, related_name='on', to=settings.AUTH_USER_MODEL),
        ),
    ]
