# Generated by Django 2.0.5 on 2019-01-29 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0058_auto_20190127_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulos',
            name='links',
        ),
        migrations.RemoveField(
            model_name='series',
            name='fecha_de_publicacion',
        ),
        migrations.AddField(
            model_name='capitulos',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='fecha_de_lanzamiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='capitulos',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
