# Generated by Django 2.0.5 on 2019-04-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0061_series_theid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
