# Generated by Django 2.0.5 on 2019-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0062_auto_20190415_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='titulo_original',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
