# Generated by Django 2.0.5 on 2019-04-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0063_auto_20190415_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='palabra_clave',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tag7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tema',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='titulo_original',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
