# Generated by Django 2.0.5 on 2019-04-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0065_auto_20190415_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='fecha_de_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='palabra_clave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='tema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
