# Generated by Django 2.0.5 on 2019-04-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0066_auto_20190415_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='sinopsis',
            field=models.CharField(max_length=800),
        ),
    ]
