# Generated by Django 2.0.5 on 2019-04-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0068_auto_20190416_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='sinopsis',
            field=models.CharField(max_length=2000),
        ),
    ]
