# Generated by Django 2.0.5 on 2019-04-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0069_auto_20190423_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='nombre_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
