# Generated by Django 2.0.5 on 2018-12-29 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='static')),
                ('contenido', models.TextField()),
                ('hitcount_day', models.IntegerField(default=0)),
                ('hitcount_week', models.IntegerField(default=0)),
                ('hitcount_month', models.IntegerField(default=0)),
                ('hitcount_ever', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('img', models.ImageField(upload_to='static')),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ManyToManyField(related_name='media', to='news.NewsMedia'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='news.NewsTags'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
