# Generated by Django 2.0.5 on 2018-12-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181229_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(default=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
