# Generated by Django 2.0.5 on 2018-12-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181229_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
