# Generated by Django 2.0.5 on 2018-12-30 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0070_auto_20181215_0024'),
        ('series', '0053_auto_20181210_2318'),
        ('news', '0004_auto_20181229_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas'),
        ),
        migrations.AddField(
            model_name='article',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
