# Generated by Django 2.0.5 on 2018-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_search',
            field=models.SlugField(null=True),
        ),
    ]
