# Generated by Django 2.0.5 on 2018-12-31 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_article_slug_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion_Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion', models.DecimalField(blank=True, choices=[(1, 'uno'), (1.5, 'uno_y_medio'), (2, 'dos'), (2.5, 'dos_y_medio'), (3, 'tres'), (3.5, 'tres_y_medio'), (4, 'cuatro'), (4.5, 'cuatro_y_medio'), (5, 'cinco')], decimal_places=1, default=1, max_digits=5, null=True)),
                ('publish', models.DateField(auto_now=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
