# Generated by Django 2.0.5 on 2018-11-24 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0023_auto_20180629_0159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Unread', max_length=10)),
                ('action', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=15)),
                ('creadores', models.ManyToManyField(blank=True, related_name='generadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampe', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ManyToManyField(blank=True, to='notificaciones.Evento')),
                ('komentario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentario', to='comentarios.Post')),
                ('user_a_notificar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
