# Generated by Django 2.0.5 on 2018-11-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_auto_20180521_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='action',
            new_name='mensaje',
        ),
    ]
