# Generated by Django 2.0.5 on 2018-11-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_auto_20181124_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='noti_de_evento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='notificaciones.Notificaciones'),
            preserve_default=False,
        ),
    ]
