# Generated by Django 2.0.5 on 2018-11-24 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_evento_noti_de_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='timestampe',
        ),
        migrations.AddField(
            model_name='evento',
            name='timestampe',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
