# Generated by Django 2.0.5 on 2018-11-27 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_compartir'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartir',
            name='timestampc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
