# Generated by Django 2.0.5 on 2018-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0008_auto_20181127_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartir',
            name='event',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='compartir',
            name='mensaje',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compartir',
            name='status',
            field=models.CharField(default='Unread', max_length=10),
        ),
    ]
