# Generated by Django 2.0.5 on 2018-12-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0010_compartir_user_who_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='komentario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentario', to='comentarios.Post'),
        ),
    ]
