# Generated by Django 2.0.5 on 2018-12-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0023_auto_20180629_0159'),
        ('notificaciones', '0011_auto_20181201_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='respm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respm', to='comentarios.Answerd'),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='komentario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentario', to='comentarios.Post'),
        ),
    ]
