# Generated by Django 2.0.5 on 2018-12-31 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20181231_1402'),
        ('notificaciones', '0013_auto_20181201_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartir',
            name='articulo_to_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Article'),
        ),
    ]
