# Generated by Django 2.0.5 on 2018-05-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('Cover', models.ImageField(upload_to=None)),
                ('fecha_de_lanzamiento', models.DateField()),
                ('director', models.CharField(max_length=30)),
                ('reparto', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('sinopsis', models.CharField(max_length=400)),
            ],
        ),
    ]
