# Generated by Django 2.0.5 on 2018-05-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='Cover',
            field=models.ImageField(upload_to='static'),
        ),
    ]
