# Generated by Django 2.0.5 on 2018-05-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20180521_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
