# Generated by Django 2.0.5 on 2018-05-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_auto_20180521_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
