# Generated by Django 2.0.5 on 2018-05-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_auto_20180524_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_de_estreno', models.DateField()),
                ('sinopsis', models.TextField()),
                ('reparto', models.TextField()),
                ('trailer_cover', models.ImageField(upload_to='static')),
                ('links', models.TextField()),
                ('genero', models.CharField(choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen')], default='ACC', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Trailers',
            },
        ),
    ]
