# Generated by Django 2.0.5 on 2018-05-28 01:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_trailers'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen')], max_length=22),
        ),
    ]
