# Generated by Django 2.0.5 on 2018-05-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_peliculas_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='tags',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='tags',
            field=models.ManyToManyField(related_name='peliculas', to='peliculas.Tag'),
        ),
    ]
