# Generated by Django 2.0.5 on 2018-05-29 17:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0009_auto_20180529_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='tags',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen')], max_length=22),
        ),
    ]
