# Generated by Django 2.0.5 on 2018-05-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0010_auto_20180529_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='tags',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='tags',
            field=models.ManyToManyField(blank=True, to='peliculas.Tag'),
        ),
    ]
