# Generated by Django 2.0.5 on 2018-05-29 21:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0012_auto_20180529_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, unique=True),
        ),
    ]
