# Generated by Django 2.0.5 on 2018-05-29 21:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0013_auto_20180529_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen')], max_length=22, unique=True),
        ),
    ]
