# Generated by Django 2.0.5 on 2018-05-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0015_auto_20180529_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='tag', to='peliculas.Tag'),
        ),
    ]
