# Generated by Django 2.0.5 on 2018-05-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0018_auto_20180530_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='personaje_fname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
