# Generated by Django 2.0.5 on 2018-05-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0019_cast_personaje_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='reparto',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='reparto',
            field=models.ManyToManyField(blank=True, to='peliculas.Cast'),
        ),
    ]
