# Generated by Django 2.0.5 on 2018-05-30 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0020_auto_20180530_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje', models.CharField(blank=True, max_length=50)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas')),
            ],
        ),
    ]
