# Generated by Django 2.0.5 on 2018-05-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0021_personajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='personaje_fname',
        ),
        migrations.AddField(
            model_name='cast',
            name='personaje_fname',
            field=models.ManyToManyField(blank=True, to='peliculas.Personajes'),
        ),
    ]
