# Generated by Django 2.0.5 on 2018-05-31 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0023_auto_20180530_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailers',
            name='fecha_de_subida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trailers',
            name='genero',
            field=models.CharField(choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'SciFi'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen')], default='ACC', max_length=20),
        ),
    ]
