# Generated by Django 2.0.5 on 2018-05-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0024_auto_20180530_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='portada',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
