# Generated by Django 2.0.5 on 2018-06-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0025_peliculas_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='tags',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='palabra_clave',
            field=models.CharField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('#MARVEL', 'Marvel')], max_length=20),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='tema',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
