# Generated by Django 2.0.5 on 2018-06-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0027_votacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='picture',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
