# Generated by Django 2.0.5 on 2018-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0029_auto_20180606_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'AVENTURA'), ('ANI', 'ANIMACIÓN'), ('COME', 'COMEDIA')], max_length=20),
        ),
    ]
