# Generated by Django 2.0.5 on 2018-06-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0030_auto_20180606_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='reportes',
            field=models.IntegerField(default=0),
        ),
    ]
