# Generated by Django 2.0.5 on 2018-06-09 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peliculas', '0031_peliculas_reportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='ver_mas_tarde',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
