# Generated by Django 2.0.5 on 2018-06-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0034_peliculas_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='view_time',
            field=models.IntegerField(default=0),
        ),
    ]
