# Generated by Django 2.0.5 on 2018-06-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0036_auto_20180611_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailers',
            name='fecha_de_estreno',
        ),
        migrations.RemoveField(
            model_name='trailers',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='trailers',
            name='reparto',
        ),
        migrations.RemoveField(
            model_name='trailers',
            name='sinopsis',
        ),
    ]
