# Generated by Django 2.0.5 on 2018-06-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0013_series_director'),
        ('peliculas', '0037_auto_20180612_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='personajes',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas'),
        ),
    ]
