# Generated by Django 2.0.5 on 2018-06-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0028_auto_20180614_1407'),
        ('peliculas', '0038_auto_20180612_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='fecha',
            field=models.ManyToManyField(blank=True, to='series.Vermastarde'),
        ),
    ]
