# Generated by Django 2.0.5 on 2018-06-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0040_auto_20180614_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='openload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='rapidvideo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='streamago',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='vidoza',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='webtorrent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
