# Generated by Django 2.0.5 on 2018-06-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0042_auto_20180617_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='publish',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
