# Generated by Django 2.0.5 on 2018-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0043_votacion_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='hitcount',
            field=models.IntegerField(default=0),
        ),
    ]
