# Generated by Django 2.0.5 on 2018-06-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0044_peliculas_hitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitcount', models.IntegerField(default=0)),
                ('publish', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='hitcount',
        ),
        migrations.AddField(
            model_name='hitcount',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas'),
        ),
    ]
