# Generated by Django 2.0.5 on 2018-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0045_auto_20180620_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('MIS', 'Misterio')], max_length=20),
        ),
    ]
