# Generated by Django 2.0.5 on 2018-06-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0046_auto_20180624_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
