# Generated by Django 2.0.5 on 2018-06-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0047_peliculas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
