# Generated by Django 2.0.5 on 2018-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0048_auto_20180626_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='genero2',
            field=models.CharField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('MIS', 'Misterio')], max_length=20, null=True),
        ),
    ]
