# Generated by Django 2.0.5 on 2018-07-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0049_peliculas_genero2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitcount',
            name='expired',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
