# Generated by Django 2.0.5 on 2018-07-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0050_hitcount_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
