# Generated by Django 2.0.5 on 2018-07-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0051_auto_20180701_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='personajes',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='personajes',
            name='serie',
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='reparto',
            field=models.ManyToManyField(blank=True, to='peliculas.Personajes'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='personaje',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
