# Generated by Django 2.0.5 on 2018-07-03 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peliculas', '0053_auto_20180702_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.ManyToManyField(related_name='action', to=settings.AUTH_USER_MODEL)),
                ('animacion', models.ManyToManyField(related_name='animation', to=settings.AUTH_USER_MODEL)),
                ('aventura', models.ManyToManyField(related_name='adventure', to=settings.AUTH_USER_MODEL)),
                ('bibliografico', models.ManyToManyField(related_name='bibliografic', to=settings.AUTH_USER_MODEL)),
                ('ciencia_ficcion', models.ManyToManyField(related_name='science_fiction', to=settings.AUTH_USER_MODEL)),
                ('comedia', models.ManyToManyField(related_name='comedy', to=settings.AUTH_USER_MODEL)),
                ('crimen', models.ManyToManyField(related_name='cryme', to=settings.AUTH_USER_MODEL)),
                ('documental', models.ManyToManyField(related_name='documental', to=settings.AUTH_USER_MODEL)),
                ('drama', models.ManyToManyField(related_name='drama', to=settings.AUTH_USER_MODEL)),
                ('mistero', models.ManyToManyField(related_name='mistery', to=settings.AUTH_USER_MODEL)),
                ('romance', models.ManyToManyField(related_name='romance', to=settings.AUTH_USER_MODEL)),
                ('terror', models.ManyToManyField(related_name='terror', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
