# Generated by Django 2.0.5 on 2018-07-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0054_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='generos',
            name='genero_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
