# Generated by Django 2.0.5 on 2018-07-04 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peliculas', '0055_generos_genero_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_name', models.CharField(max_length=40, null=True, unique=True)),
                ('accion', models.ManyToManyField(related_name='action', to=settings.AUTH_USER_MODEL)),
                ('animacion', models.ManyToManyField(related_name='animation', to=settings.AUTH_USER_MODEL)),
                ('aventura', models.ManyToManyField(related_name='adventure', to=settings.AUTH_USER_MODEL)),
                ('ciencia_ficcion', models.ManyToManyField(related_name='science_fiction', to=settings.AUTH_USER_MODEL)),
                ('comedia', models.ManyToManyField(related_name='comedy', to=settings.AUTH_USER_MODEL)),
                ('crimen', models.ManyToManyField(related_name='cryme', to=settings.AUTH_USER_MODEL)),
                ('documental', models.ManyToManyField(related_name='documental', to=settings.AUTH_USER_MODEL)),
                ('drama', models.ManyToManyField(related_name='drama', to=settings.AUTH_USER_MODEL)),
                ('fantasia', models.ManyToManyField(related_name='fantasy', to=settings.AUTH_USER_MODEL)),
                ('romance', models.ManyToManyField(related_name='romance', to=settings.AUTH_USER_MODEL)),
                ('suspenso', models.ManyToManyField(related_name='suspense', to=settings.AUTH_USER_MODEL)),
                ('terror', models.ManyToManyField(related_name='terror', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='generos',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='animacion',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='aventura',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='bibliografico',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='ciencia_ficcion',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='comedia',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='crimen',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='documental',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='mistero',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='romance',
        ),
        migrations.RemoveField(
            model_name='generos',
            name='terror',
        ),
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
