# Generated by Django 2.0.5 on 2018-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0056_auto_20180703_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('DOCU', 'Documental'), ('ROM', 'Romance'), ('FANT', 'Fantasia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='genero2',
            field=models.CharField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('DOCU', 'Documental'), ('ROM', 'Romance'), ('FANT', 'Fantasia')], max_length=20, null=True),
        ),
    ]
