# Generated by Django 2.0.5 on 2018-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0057_auto_20180704_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='view_time',
            new_name='run_time',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='palabra_clave',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='tag_principal',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='titulo_orinal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='tag1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='tag2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='tag3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='tema',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
