# Generated by Django 2.0.5 on 2018-07-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0058_auto_20180709_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
