# Generated by Django 2.0.5 on 2018-07-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0060_auto_20180709_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='picture',
        ),
    ]
