# Generated by Django 2.0.5 on 2018-07-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0061_remove_cast_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='sinopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
