# Generated by Django 2.0.5 on 2018-07-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0062_auto_20180709_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='webtorrent',
            new_name='streamcloud',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='vidlox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
