# Generated by Django 2.0.5 on 2018-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0063_auto_20180709_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='webtorrent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
