# Generated by Django 2.0.5 on 2018-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0064_peliculas_webtorrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='webtorrent',
            new_name='servidor1',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='servidor2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='servidor3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='servidor4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
