# Generated by Django 2.0.5 on 2018-12-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0065_auto_20181208_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitcount',
            name='hitcount_ever',
            field=models.IntegerField(default=0),
        ),
    ]
