# Generated by Django 2.0.5 on 2018-12-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0068_auto_20181214_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda_y_etiquetas',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
