# Generated by Django 2.0.5 on 2018-12-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0069_busqueda_y_etiquetas_resuelto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='otras_etiquetas_y_busquedas',
            field=models.ManyToManyField(blank=True, related_name='otras_etiquetas_y_busquedas', to='peliculas.Busqueda_y_etiquetas'),
        ),
    ]
