# Generated by Django 2.0.5 on 2019-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0070_auto_20181215_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='genero3',
            field=models.CharField(blank=True, choices=[('ACC', 'Acción'), ('DRA', 'Drama'), ('SC', 'Ciencia_Ficción'), ('TER', 'Terror'), ('SUS', 'Suspenso'), ('CRI', 'Crimen'), ('AVEN', 'Aventura'), ('ANI', 'Animación'), ('COME', 'Comedia'), ('DOCU', 'Documental'), ('ROM', 'Romance'), ('FANT', 'Fantasia')], max_length=20, null=True),
        ),
    ]
