# Generated by Django 2.0.5 on 2019-01-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0071_peliculas_genero3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
