# Generated by Django 2.0.5 on 2019-02-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0072_auto_20190122_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='theid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
