# Generated by Django 2.0.5 on 2019-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0073_peliculas_theid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='theid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
