# Generated by Django 2.0.5 on 2019-03-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0074_auto_20190216_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='CoverImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='PortadaImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
