# Generated by Django 2.0.5 on 2019-03-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0075_auto_20190326_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='CoverImg',
            field=models.ImageField(blank=True, null=True, upload_to='comprimidas'),
        ),
    ]
