# Generated by Django 2.0.5 on 2019-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0078_solicitar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='fecha_de_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='run_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
