# Generated by Django 2.0.5 on 2019-04-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0079_auto_20190418_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='director',
            field=models.CharField(max_length=60),
        ),
    ]
