# Generated by Django 2.0.5 on 2018-06-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vermas_tarde', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='peliculas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas'),
        ),
        migrations.AlterField(
            model_name='vermastarde',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
    ]
