# Generated by Django 2.0.5 on 2018-07-07 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vermas_tarde', '0002_auto_20180614_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vermastarde',
            name='peliculas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.Peliculas'),
        ),
    ]
