# Generated by Django 2.0.5 on 2018-06-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0026_auto_20180601_1754'),
        ('comentarios', '0002_auto_20180602_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='peliculas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas'),
            preserve_default=False,
        ),
    ]
