# Generated by Django 2.0.5 on 2018-06-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_auto_20180602_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='peliculas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas'),
        ),
    ]
