# Generated by Django 2.0.5 on 2018-06-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0012_series_puntuacion'),
        ('comentarios', '0012_auto_20180605_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AlterField(
            model_name='post',
            name='peliculas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.Peliculas'),
        ),
    ]
