# Generated by Django 2.0.5 on 2018-06-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0035_auto_20180617_1334'),
        ('comentarios', '0014_auto_20180613_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capitulos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Capitulos'),
        ),
    ]
