# Generated by Django 2.0.5 on 2018-06-27 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0015_post_capitulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerd',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comentarios.Post'),
        ),
        migrations.AddField(
            model_name='answerd',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='respuestas',
            field=models.ManyToManyField(blank=True, to='comentarios.Answerd'),
        ),
    ]
