# Generated by Django 2.0.5 on 2018-06-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0016_auto_20180627_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unvote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
