# Generated by Django 2.0.5 on 2018-06-27 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0017_auto_20180627_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote',
        ),
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.ManyToManyField(blank=True, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
