# Generated by Django 2.0.5 on 2018-06-27 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0018_auto_20180627_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unvote',
        ),
        migrations.AddField(
            model_name='post',
            name='unvote',
            field=models.ManyToManyField(blank=True, related_name='unvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
