# Generated by Django 2.0.5 on 2018-06-27 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0019_auto_20180627_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerd',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerd',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
