# Generated by Django 2.0.5 on 2018-06-29 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0020_auto_20180627_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportar', models.CharField(choices=[('Spoiler', 'Spoiler'), ('Muestra odio o violencia', 'Muestra odio o violencia'), ('Spam o Contenido comercial', 'Spam o Contenido comercial')], max_length=20)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.Post')),
                ('reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.Answerd')),
            ],
        ),
    ]
