# Generated by Django 2.0.5 on 2018-06-29 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0021_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.Post'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.Answerd'),
        ),
    ]
