# Generated by Django 2.0.5 on 2018-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0022_auto_20180629_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='reportar',
            field=models.CharField(choices=[('Spoiler', 'Spoiler'), ('Muestra odio o violencia', 'Muestra odio o violencia'), ('Spam o Contenido comercial', 'Spam o Contenido comercial')], max_length=60),
        ),
    ]
