# Generated by Django 2.0.5 on 2019-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0024_post_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerd',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
