# Generated by Django 2.0.5 on 2019-01-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0025_auto_20190101_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1300),
        ),
    ]
