# Generated by Django 2.0.5 on 2019-01-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0027_auto_20190122_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerd',
            name='respuesta',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1500),
        ),
    ]
