# Generated by Django 2.0.5 on 2018-06-02 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20180602_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='perfil_img',
            field=models.ImageField(default='static/default.png', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
