# Generated by Django 2.0.5 on 2018-06-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180602_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='perfil_img',
            field=models.ImageField(blank=True, default='static/default.png', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='staff',
            field=models.BooleanField(default=True),
        ),
    ]
