# Generated by Django 2.0.5 on 2018-06-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20180624_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
