# Generated by Django 2.0.5 on 2018-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20180626_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
