# Generated by Django 2.0.5 on 2018-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20180701_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codde',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
