# Generated by Django 2.0.5 on 2018-11-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_profile_codde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='codde',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
