# Generated by Django 2.0.5 on 2018-12-10 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_profile_amigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_principal', models.CharField(blank=True, max_length=40)),
                ('tema', models.CharField(blank=True, max_length=40)),
                ('tag1', models.CharField(blank=True, max_length=40)),
                ('tag2', models.CharField(blank=True, max_length=40)),
                ('tag3', models.CharField(blank=True, max_length=40)),
                ('week_recomendation', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
