# Generated by Django 2.0.5 on 2018-12-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0065_auto_20181208_1336'),
        ('usuarios', '0017_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='tag3',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='tag_principal',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='tema',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='expired',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='week_recomendation',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='week_recomendation',
            field=models.ManyToManyField(blank=True, related_name='week_recomendation', to='peliculas.Peliculas'),
        ),
    ]
