# Generated by Django 2.0.5 on 2018-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20181210_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='expired',
            field=models.DateTimeField(),
        ),
    ]
