# Generated by Django 2.0.5 on 2018-12-11 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20181210_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 6, 9, 35, 512716, tzinfo=utc)),
        ),
    ]
