# Generated by Django 2.0.5 on 2018-12-11 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20181211_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
