# Generated by Django 2.0.5 on 2018-12-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_auto_20181211_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_series',
            field=models.BooleanField(default=True),
        ),
    ]
