# Generated by Django 2.0.5 on 2019-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_ips_user_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='hitcount',
            field=models.IntegerField(default=0),
        ),
    ]
