# Generated by Django 2.0.5 on 2019-02-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_ips_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='endindex',
            field=models.IntegerField(default=20),
        ),
    ]
